INSERT INTO INTEREST_CATEGORY(CREATED_DATE, MODIFIED_DATE, CATEGORY) VALUES(NOW(), NOW(), '여행/나들이');
INSERT INTO INTEREST_CATEGORY(CREATED_DATE, MODIFIED_DATE, CATEGORY) VALUES(NOW(), NOW(), '플랜테리어');
INSERT INTO INTEREST_CATEGORY(CREATED_DATE, MODIFIED_DATE, CATEGORY) VALUES(NOW(), NOW(), '식물 가꾸기');




